/* The following code was generated by JFlex 1.6.1 */

package proyecto_compi;

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/proyecto_compi/lexer.flex</tt>
 */
public class lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\3\1\64\1\64\1\2\22\0\1\5\1\27\1\11"+
    "\2\0\1\10\1\55\1\17\1\31\1\32\1\7\1\33\1\37\1\34"+
    "\1\63\1\6\12\1\1\25\1\56\1\36\1\26\1\35\1\20\1\0"+
    "\32\15\1\51\1\20\1\52\1\0\1\21\1\0\1\41\1\61\1\14"+
    "\1\12\1\45\1\43\1\15\1\40\1\30\1\15\1\62\1\57\1\44"+
    "\1\22\1\50\1\42\1\15\1\24\1\13\1\23\1\46\1\47\1\60"+
    "\3\15\1\53\1\16\1\54\7\0\1\64\32\0\1\20\11\0\1\20"+
    "\12\0\1\20\4\0\1\20\5\0\27\20\1\0\37\20\1\0\u01ca\20"+
    "\4\0\14\20\16\0\5\20\7\0\1\20\1\0\1\20\21\0\165\20"+
    "\1\0\2\20\2\0\4\20\1\0\1\20\6\0\1\20\1\0\3\20"+
    "\1\0\1\20\1\0\24\20\1\0\123\20\1\0\213\20\1\0\255\20"+
    "\1\0\46\20\2\0\1\20\7\0\47\20\11\0\55\20\1\0\1\20"+
    "\1\0\2\20\1\0\2\20\1\0\1\20\10\0\33\20\5\0\3\20"+
    "\35\0\13\20\5\0\100\20\12\20\4\0\146\20\1\0\10\20\2\0"+
    "\12\20\1\0\6\20\12\20\3\20\2\0\1\20\20\0\73\20\2\0"+
    "\145\20\16\0\12\20\54\20\4\0\1\20\5\0\56\20\22\0\34\20"+
    "\104\0\23\20\61\0\200\20\2\0\12\20\1\0\23\20\1\0\10\20"+
    "\2\0\2\20\2\0\26\20\1\0\7\20\1\0\1\20\3\0\4\20"+
    "\2\0\11\20\2\0\2\20\2\0\4\20\10\0\1\20\4\0\2\20"+
    "\1\0\5\20\2\0\12\20\2\20\17\0\3\20\1\0\6\20\4\0"+
    "\2\20\2\0\26\20\1\0\7\20\1\0\2\20\1\0\2\20\1\0"+
    "\2\20\2\0\1\20\1\0\5\20\4\0\2\20\2\0\3\20\3\0"+
    "\1\20\7\0\4\20\1\0\1\20\7\0\12\20\6\20\13\0\3\20"+
    "\1\0\11\20\1\0\3\20\1\0\26\20\1\0\7\20\1\0\2\20"+
    "\1\0\5\20\2\0\12\20\1\0\3\20\1\0\3\20\2\0\1\20"+
    "\17\0\4\20\2\0\12\20\21\0\3\20\1\0\10\20\2\0\2\20"+
    "\2\0\26\20\1\0\7\20\1\0\2\20\1\0\5\20\2\0\11\20"+
    "\2\0\2\20\2\0\3\20\10\0\2\20\4\0\2\20\1\0\5\20"+
    "\2\0\12\20\1\0\1\20\20\0\2\20\1\0\6\20\3\0\3\20"+
    "\1\0\4\20\3\0\2\20\1\0\1\20\1\0\2\20\3\0\2\20"+
    "\3\0\3\20\3\0\14\20\4\0\5\20\3\0\3\20\1\0\4\20"+
    "\2\0\1\20\6\0\1\20\16\0\12\20\20\0\4\20\1\0\10\20"+
    "\1\0\3\20\1\0\27\20\1\0\20\20\3\0\10\20\1\0\3\20"+
    "\1\0\4\20\7\0\2\20\1\0\2\20\6\0\4\20\2\0\12\20"+
    "\21\0\3\20\1\0\10\20\1\0\3\20\1\0\27\20\1\0\12\20"+
    "\1\0\5\20\2\0\11\20\1\0\3\20\1\0\4\20\7\0\2\20"+
    "\7\0\1\20\1\0\4\20\2\0\12\20\1\0\2\20\16\0\3\20"+
    "\1\0\10\20\1\0\3\20\1\0\51\20\2\0\10\20\1\0\3\20"+
    "\1\0\5\20\10\0\1\20\10\0\4\20\2\0\12\20\12\0\6\20"+
    "\2\0\2\20\1\0\22\20\3\0\30\20\1\0\11\20\1\0\1\20"+
    "\2\0\7\20\3\0\1\20\4\0\6\20\1\0\1\20\1\0\10\20"+
    "\6\0\12\20\2\0\2\20\15\0\72\20\5\0\17\20\1\0\12\20"+
    "\47\0\2\20\1\0\1\20\2\0\2\20\1\0\1\20\2\0\1\20"+
    "\6\0\4\20\1\0\7\20\1\0\3\20\1\0\1\20\1\0\1\20"+
    "\2\0\2\20\1\0\15\20\1\0\3\20\2\0\5\20\1\0\1\20"+
    "\1\0\6\20\2\0\12\20\2\0\4\20\40\0\1\20\27\0\2\20"+
    "\6\0\12\20\13\0\1\20\1\0\1\20\1\0\1\20\4\0\12\20"+
    "\1\0\44\20\4\0\24\20\1\0\22\20\1\0\44\20\11\0\1\20"+
    "\71\0\100\20\12\20\6\0\100\20\12\20\4\20\2\0\46\20\1\0"+
    "\1\20\5\0\1\20\2\0\53\20\1\0\u014d\20\1\0\4\20\2\0"+
    "\7\20\1\0\1\20\1\0\4\20\2\0\51\20\1\0\4\20\2\0"+
    "\41\20\1\0\4\20\2\0\7\20\1\0\1\20\1\0\4\20\2\0"+
    "\17\20\1\0\71\20\1\0\4\20\2\0\103\20\2\0\3\20\40\0"+
    "\20\20\20\0\125\20\14\0\u026c\20\2\0\21\20\1\20\32\20\5\0"+
    "\113\20\3\0\13\20\7\0\15\20\1\0\7\20\13\0\25\20\13\0"+
    "\24\20\14\0\15\20\1\0\3\20\1\0\2\20\14\0\124\20\3\0"+
    "\1\20\4\0\2\20\2\0\12\20\41\0\3\20\2\0\12\20\6\0"+
    "\130\20\10\0\53\20\5\0\106\20\12\0\37\20\1\0\14\20\4\0"+
    "\14\20\12\0\12\20\36\20\2\0\5\20\13\0\54\20\4\0\32\20"+
    "\6\0\12\20\46\0\34\20\4\0\77\20\1\0\35\20\2\0\1\20"+
    "\12\20\6\0\12\20\15\0\1\20\10\0\17\20\101\0\114\20\4\0"+
    "\12\20\21\0\11\20\14\0\60\20\12\20\72\20\14\0\70\20\10\0"+
    "\12\20\3\0\3\20\12\20\44\20\122\0\3\20\1\0\43\20\1\0"+
    "\2\20\6\0\366\20\6\0\u011a\20\2\0\6\20\2\0\46\20\2\0"+
    "\6\20\2\0\10\20\1\0\1\20\1\0\1\20\1\0\1\20\1\0"+
    "\37\20\2\0\65\20\1\0\7\20\1\0\1\20\3\0\3\20\1\0"+
    "\7\20\3\0\4\20\2\0\6\20\4\0\15\20\5\0\3\20\1\0"+
    "\7\20\3\0\13\20\35\0\1\64\1\64\5\0\1\20\17\0\2\20"+
    "\23\0\1\20\12\0\1\20\21\0\1\20\15\0\1\20\20\0\15\20"+
    "\63\0\41\20\21\0\1\20\4\0\1\20\2\0\12\20\1\0\1\20"+
    "\3\0\5\20\6\0\1\20\1\0\1\20\1\0\1\20\1\0\4\20"+
    "\1\0\13\20\2\0\4\20\5\0\5\20\4\0\1\20\21\0\51\20"+
    "\u032d\0\64\20\u0716\0\57\20\1\0\57\20\1\0\205\20\6\0\11\20"+
    "\14\0\46\20\1\0\1\20\5\0\1\20\2\0\70\20\7\0\1\20"+
    "\17\0\30\20\11\0\7\20\1\0\7\20\1\0\7\20\1\0\7\20"+
    "\1\0\7\20\1\0\7\20\1\0\7\20\1\0\7\20\1\0\40\20"+
    "\57\0\1\20\u01d0\0\1\20\4\0\3\20\31\0\17\20\1\0\5\20"+
    "\2\0\5\20\4\0\126\20\2\0\2\20\2\0\3\20\1\0\132\20"+
    "\1\0\4\20\5\0\51\20\3\0\136\20\21\0\33\20\65\0\20\20"+
    "\u0200\0\u19b6\20\112\0\u51cd\20\63\0\u048d\20\103\0\56\20\2\0\u010d\20"+
    "\3\0\20\20\12\20\2\20\24\0\63\20\1\0\12\20\1\0\37\20"+
    "\1\0\123\20\45\0\11\20\2\0\147\20\2\0\4\20\1\0\36\20"+
    "\2\0\2\20\105\0\61\20\30\0\64\20\14\0\105\20\13\0\12\20"+
    "\6\0\30\20\3\0\1\20\4\0\12\20\44\20\2\0\44\20\14\0"+
    "\35\20\3\0\101\20\16\0\1\20\12\20\6\0\20\20\12\20\5\20"+
    "\1\0\67\20\11\0\16\20\2\0\12\20\6\0\27\20\3\0\111\20"+
    "\30\0\3\20\2\0\20\20\2\0\5\20\12\0\6\20\2\0\6\20"+
    "\2\0\6\20\11\0\7\20\1\0\7\20\1\0\53\20\1\0\4\20"+
    "\4\0\2\20\132\0\53\20\1\0\2\20\2\0\12\20\6\0\u2ba4\20"+
    "\14\0\27\20\4\0\61\20\u2104\0\u016e\20\2\0\152\20\46\0\7\20"+
    "\14\0\5\20\5\0\14\20\1\0\15\20\1\0\5\20\1\0\1\20"+
    "\1\0\2\20\1\0\2\20\1\0\154\20\41\0\u016b\20\22\0\100\20"+
    "\2\0\66\20\50\0\14\20\4\0\20\20\20\0\16\20\5\0\2\20"+
    "\30\0\3\20\40\0\5\20\1\0\207\20\23\0\12\20\7\0\32\20"+
    "\4\0\1\20\1\0\32\20\13\0\131\20\3\0\6\20\2\0\6\20"+
    "\2\0\6\20\2\0\3\20\43\0\14\20\1\0\32\20\1\0\23\20"+
    "\1\0\2\20\1\0\17\20\2\0\16\20\42\0\173\20\105\0\65\20"+
    "\210\0\1\20\202\0\35\20\3\0\61\20\17\0\1\20\37\0\40\20"+
    "\20\0\33\20\5\0\53\20\5\0\36\20\2\0\44\20\4\0\10\20"+
    "\1\0\5\20\52\0\236\20\2\0\12\20\126\0\50\20\10\0\64\20"+
    "\234\0\u0137\20\11\0\26\20\12\0\10\20\230\0\6\20\2\0\1\20"+
    "\1\0\54\20\1\0\2\20\3\0\1\20\2\0\27\20\12\0\27\20"+
    "\11\0\37\20\141\0\26\20\12\0\32\20\106\0\70\20\6\0\2\20"+
    "\100\0\4\20\1\0\2\20\5\0\10\20\1\0\3\20\1\0\33\20"+
    "\4\0\3\20\4\0\1\20\40\0\35\20\3\0\35\20\43\0\10\20"+
    "\1\0\36\20\31\0\66\20\12\0\26\20\12\0\23\20\15\0\22\20"+
    "\156\0\111\20\u03b7\0\107\20\37\0\12\20\17\0\74\20\25\0\31\20"+
    "\7\0\12\20\6\0\65\20\1\0\12\20\20\0\44\20\2\0\1\20"+
    "\11\0\105\20\13\0\12\20\1\20\45\0\22\20\1\0\45\20\170\0"+
    "\73\20\5\0\12\20\7\0\3\20\1\0\10\20\2\0\2\20\2\0"+
    "\26\20\1\0\7\20\1\0\2\20\1\0\5\20\2\0\11\20\2\0"+
    "\2\20\2\0\3\20\11\0\1\20\5\0\7\20\2\0\7\20\3\0"+
    "\5\20\u010b\0\106\20\1\0\1\20\10\0\12\20\246\0\66\20\2\0"+
    "\11\20\77\0\101\20\3\0\1\20\13\0\12\20\46\0\70\20\10\0"+
    "\12\20\u01d6\0\100\20\12\20\25\0\1\20\u01c0\0\71\20\u0507\0\u0399\20"+
    "\147\0\157\20\u0b91\0\u042f\20\u33d1\0\u0239\20\7\0\37\20\1\0\12\20"+
    "\146\0\36\20\2\0\5\20\13\0\67\20\11\0\4\20\14\0\12\20"+
    "\11\0\25\20\5\0\23\20\u0370\0\105\20\13\0\57\20\20\0\21\20"+
    "\u4060\0\2\20\u0bfe\0\153\20\5\0\15\20\3\0\11\20\7\0\12\20"+
    "\3\0\2\20\u14c6\0\5\20\3\0\6\20\10\0\10\20\2\0\7\20"+
    "\36\0\4\20\224\0\3\20\u01bb\0\125\20\1\0\107\20\1\0\2\20"+
    "\2\0\1\20\2\0\2\20\2\0\4\20\1\0\14\20\1\0\1\20"+
    "\1\0\7\20\1\0\101\20\1\0\4\20\2\0\10\20\1\0\7\20"+
    "\1\0\34\20\1\0\4\20\1\0\5\20\1\0\1\20\3\0\7\20"+
    "\1\0\u0154\20\2\0\31\20\1\0\31\20\1\0\37\20\1\0\31\20"+
    "\1\0\37\20\1\0\31\20\1\0\37\20\1\0\31\20\1\0\37\20"+
    "\1\0\31\20\1\0\10\20\2\0\62\20\u1000\0\305\20\13\0\7\20"+
    "\u0529\0\4\20\1\0\33\20\1\0\2\20\1\0\1\20\2\0\1\20"+
    "\1\0\12\20\1\0\4\20\1\0\1\20\1\0\1\20\6\0\1\20"+
    "\4\0\1\20\1\0\1\20\1\0\1\20\1\0\3\20\1\0\2\20"+
    "\1\0\1\20\2\0\1\20\1\0\1\20\1\0\1\20\1\0\1\20"+
    "\1\0\1\20\1\0\2\20\1\0\1\20\2\0\4\20\1\0\7\20"+
    "\1\0\4\20\1\0\4\20\1\0\1\20\1\0\12\20\1\0\21\20"+
    "\5\0\3\20\1\0\5\20\1\0\21\20\u0274\0\32\20\6\0\32\20"+
    "\6\0\32\20\u0e76\0\ua6d7\20\51\0\u1035\20\13\0\336\20\u3fe2\0\u021e\20"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u06ed\0"+
    "\360\20\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\3\1\4\1\5\1\6\1\1"+
    "\3\7\2\1\1\7\1\10\1\11\1\12\1\7\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\5\7\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\2\7\1\30\1\3"+
    "\1\0\1\31\1\32\1\33\1\34\1\35\1\36\1\0"+
    "\1\37\2\7\1\40\1\0\1\7\1\41\1\42\1\7"+
    "\1\43\1\7\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\5\7\1\52\2\7\2\0\2\7\1\53\1\7\1\54"+
    "\2\7\1\55\5\7\1\0\1\7\1\56\1\7\1\57"+
    "\2\7\1\60\1\61\1\62\2\7\1\63\1\64\3\7"+
    "\1\65\1\66\1\67\1\70\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\65\0\324\0\u0109\0\u013e"+
    "\0\u0173\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6"+
    "\0\65\0\u031b\0\u0350\0\u0385\0\65\0\65\0\u03ba\0\u03ef"+
    "\0\u0424\0\u0459\0\65\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562"+
    "\0\65\0\65\0\65\0\65\0\u0597\0\65\0\u05cc\0\u0601"+
    "\0\65\0\u0636\0\u066b\0\65\0\65\0\65\0\65\0\65"+
    "\0\65\0\u01a8\0\65\0\u06a0\0\u06d5\0\65\0\u070a\0\u073f"+
    "\0\65\0\65\0\u0774\0\u01dd\0\u07a9\0\65\0\65\0\65"+
    "\0\65\0\65\0\65\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2"+
    "\0\65\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0\0\65"+
    "\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u01dd\0\u0af9\0\u0b2e\0\u0b63"+
    "\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\65\0\u0cd6"+
    "\0\u0d0b\0\u01dd\0\u01dd\0\u01dd\0\u0d40\0\u0d75\0\u01dd\0\65"+
    "\0\u0daa\0\u0ddf\0\u0e14\0\u01dd\0\u01dd\0\u01dd\0\u01dd\0\u01dd";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\13\1\16\1\17\2\2"+
    "\2\13\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\2\13\1\34\1\35"+
    "\1\36\1\37\1\13\1\40\1\13\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\13\1\47\1\50\1\13\1\51"+
    "\67\0\1\3\66\0\1\5\66\0\1\6\65\0\1\52"+
    "\1\53\16\0\1\54\64\0\1\55\46\0\1\56\2\0"+
    "\1\57\1\60\11\0\1\61\37\0\10\62\1\63\5\62"+
    "\1\0\31\62\6\0\4\62\1\0\1\62\1\0\1\13"+
    "\10\0\5\13\2\0\4\13\3\0\1\13\7\0\11\13"+
    "\6\0\4\13\3\0\1\13\10\0\2\13\1\64\2\13"+
    "\2\0\4\13\3\0\1\13\7\0\11\13\6\0\4\13"+
    "\3\0\1\13\10\0\5\13\2\0\4\13\3\0\1\13"+
    "\7\0\1\65\10\13\6\0\4\13\20\0\1\66\60\0"+
    "\4\67\4\0\3\67\3\0\1\67\7\0\11\67\6\0"+
    "\4\67\3\0\1\13\10\0\5\13\2\0\4\13\3\0"+
    "\1\13\7\0\5\13\1\70\3\13\6\0\4\13\30\0"+
    "\1\71\64\0\1\72\37\0\1\13\10\0\5\13\2\0"+
    "\1\13\1\73\2\13\3\0\1\13\7\0\3\13\1\74"+
    "\1\75\4\13\6\0\4\13\30\0\1\76\4\0\1\77"+
    "\57\0\1\100\5\0\1\101\56\0\1\102\64\0\1\103"+
    "\37\0\1\13\10\0\5\13\2\0\3\13\1\104\3\0"+
    "\1\13\7\0\11\13\6\0\4\13\3\0\1\13\10\0"+
    "\5\13\2\0\4\13\3\0\1\13\7\0\10\13\1\105"+
    "\6\0\4\13\3\0\1\13\10\0\5\13\2\0\4\13"+
    "\3\0\1\13\7\0\1\13\1\106\7\13\6\0\4\13"+
    "\3\0\1\13\10\0\5\13\2\0\4\13\3\0\1\13"+
    "\7\0\11\13\6\0\1\107\3\13\3\0\1\13\10\0"+
    "\5\13\2\0\4\13\3\0\1\13\7\0\10\13\1\110"+
    "\6\0\4\13\57\0\1\111\10\0\1\13\10\0\5\13"+
    "\2\0\4\13\3\0\1\13\7\0\1\112\10\13\6\0"+
    "\4\13\3\0\1\13\10\0\5\13\2\0\3\13\1\113"+
    "\3\0\1\13\7\0\11\13\6\0\4\13\2\0\2\52"+
    "\1\4\1\5\61\52\7\114\1\115\55\114\1\0\1\13"+
    "\10\0\5\13\2\0\4\13\3\0\1\13\7\0\1\13"+
    "\1\116\7\13\6\0\4\13\3\0\1\13\10\0\5\13"+
    "\2\0\4\13\3\0\1\13\7\0\1\13\1\117\7\13"+
    "\6\0\4\13\21\0\1\120\46\0\1\13\10\0\5\13"+
    "\2\0\2\13\1\121\1\13\3\0\1\13\7\0\11\13"+
    "\6\0\4\13\3\0\1\13\10\0\5\13\2\0\2\13"+
    "\1\122\1\13\3\0\1\13\7\0\11\13\6\0\4\13"+
    "\3\0\1\13\10\0\5\13\2\0\4\13\3\0\1\13"+
    "\7\0\2\13\1\123\6\13\6\0\4\13\3\0\1\13"+
    "\10\0\5\13\2\0\4\13\3\0\1\124\7\0\11\13"+
    "\6\0\4\13\3\0\1\13\10\0\5\13\2\0\3\13"+
    "\1\125\3\0\1\13\7\0\11\13\6\0\4\13\3\0"+
    "\1\13\10\0\5\13\2\0\4\13\3\0\1\126\7\0"+
    "\11\13\6\0\4\13\3\0\1\13\10\0\1\13\1\127"+
    "\3\13\2\0\4\13\3\0\1\13\7\0\11\13\6\0"+
    "\4\13\3\0\1\13\10\0\5\13\2\0\4\13\3\0"+
    "\1\130\7\0\11\13\6\0\4\13\3\0\1\13\10\0"+
    "\5\13\2\0\4\13\3\0\1\131\7\0\11\13\6\0"+
    "\4\13\3\0\1\13\10\0\5\13\2\0\4\13\3\0"+
    "\1\13\7\0\5\13\1\132\3\13\6\0\4\13\2\0"+
    "\7\114\1\133\55\114\6\0\1\5\1\115\56\0\1\13"+
    "\10\0\5\13\2\0\1\13\1\134\2\13\3\0\1\13"+
    "\7\0\11\13\6\0\4\13\3\0\1\13\10\0\5\13"+
    "\2\0\3\13\1\135\3\0\1\13\7\0\11\13\6\0"+
    "\4\13\3\0\1\13\10\0\5\13\2\0\4\13\3\0"+
    "\1\13\7\0\6\13\1\136\2\13\6\0\4\13\3\0"+
    "\1\13\5\0\1\137\2\0\5\13\2\0\4\13\3\0"+
    "\1\13\7\0\11\13\6\0\4\13\3\0\1\13\10\0"+
    "\5\13\2\0\4\13\3\0\1\13\7\0\10\13\1\140"+
    "\6\0\4\13\3\0\1\13\10\0\5\13\2\0\1\13"+
    "\1\141\2\13\3\0\1\13\7\0\11\13\6\0\4\13"+
    "\3\0\1\13\10\0\5\13\2\0\1\13\1\142\2\13"+
    "\3\0\1\13\7\0\11\13\6\0\4\13\3\0\1\13"+
    "\10\0\5\13\2\0\4\13\3\0\1\13\7\0\5\13"+
    "\1\143\3\13\6\0\4\13\3\0\1\13\10\0\1\144"+
    "\4\13\2\0\4\13\3\0\1\13\7\0\11\13\6\0"+
    "\4\13\3\0\1\13\10\0\5\13\2\0\4\13\3\0"+
    "\1\13\7\0\11\13\6\0\1\145\3\13\3\0\1\13"+
    "\10\0\5\13\2\0\4\13\3\0\1\13\7\0\1\13"+
    "\1\146\7\13\6\0\4\13\2\0\6\114\1\5\1\133"+
    "\55\114\1\0\1\13\10\0\5\13\2\0\4\13\3\0"+
    "\1\13\7\0\3\13\1\147\5\13\6\0\4\13\3\0"+
    "\1\13\5\0\1\150\2\0\5\13\2\0\4\13\3\0"+
    "\1\13\7\0\11\13\6\0\4\13\3\0\1\13\10\0"+
    "\5\13\2\0\3\13\1\151\3\0\1\13\7\0\11\13"+
    "\6\0\4\13\3\0\1\13\10\0\5\13\2\0\3\13"+
    "\1\152\3\0\1\13\7\0\11\13\6\0\4\13\3\0"+
    "\1\13\10\0\5\13\2\0\2\13\1\153\1\13\3\0"+
    "\1\13\7\0\11\13\6\0\4\13\3\0\1\13\10\0"+
    "\5\13\2\0\4\13\3\0\1\13\7\0\5\13\1\154"+
    "\3\13\6\0\4\13\3\0\1\13\10\0\5\13\2\0"+
    "\4\13\3\0\1\13\7\0\11\13\6\0\3\13\1\155"+
    "\3\0\1\13\10\0\5\13\2\0\1\13\1\156\2\13"+
    "\3\0\1\13\7\0\11\13\6\0\4\13\3\0\1\13"+
    "\10\0\5\13\2\0\2\13\1\157\1\13\3\0\1\13"+
    "\7\0\11\13\6\0\4\13\3\0\1\13\10\0\5\13"+
    "\2\0\4\13\3\0\1\13\7\0\3\13\1\160\5\13"+
    "\6\0\4\13\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3657];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\13\1\1\11\3\1\2\11"+
    "\4\1\1\11\5\1\4\11\1\1\1\11\2\1\1\11"+
    "\1\1\1\0\6\11\1\0\1\11\2\1\1\11\1\0"+
    "\1\1\2\11\3\1\6\11\5\1\1\11\2\1\2\0"+
    "\2\1\1\11\12\1\1\0\3\1\1\11\10\1\1\11"+
    "\10\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private void reportError(int line, String msg) {
        System.out.println("Lexical error at line #" + line + ": " + msg);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2732) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { reportError(yyline + 1, "Illegal character \"" + yytext() + "\"");
            }
          case 58: break;
          case 2: 
            { return new Symbol(sym.NUM,  yyline + 1, yycolumn + 1, yytext());
            }
          case 59: break;
          case 3: 
            { /*Do Nothing*/
            }
          case 60: break;
          case 4: 
            { return new Symbol(sym.OPERADORDIV,  yyline + 1, yycolumn + 1, yytext());
            }
          case 61: break;
          case 5: 
            { return new Symbol(sym.OPERADORMULTIPLICACION,  yyline + 1, yycolumn + 1, yytext());
            }
          case 62: break;
          case 6: 
            { return new Symbol(sym.MODARITMETICO,  yyline + 1, yycolumn + 1, yytext());
            }
          case 63: break;
          case 7: 
            { return new Symbol(sym.ID,  yyline + 1, yycolumn + 1, yytext());
            }
          case 64: break;
          case 8: 
            { return new Symbol(sym.DOSPUNTOS,  yyline + 1, yycolumn + 1, yytext());
            }
          case 65: break;
          case 9: 
            { return new Symbol(sym.IGUAL,  yyline + 1, yycolumn + 1, yytext());
            }
          case 66: break;
          case 10: 
            { return new Symbol(sym.NOT,  yyline + 1, yycolumn + 1, yytext());
            }
          case 67: break;
          case 11: 
            { return new Symbol(sym.PARENTESISIZQUIERDO,  yyline + 1, yycolumn + 1, yytext());
            }
          case 68: break;
          case 12: 
            { return new Symbol(sym.PARENTESISDERECHO,  yyline + 1, yycolumn + 1, yytext());
            }
          case 69: break;
          case 13: 
            { return new Symbol(sym.OPERADORSUMA,  yyline + 1, yycolumn + 1, yytext());
            }
          case 70: break;
          case 14: 
            { return new Symbol(sym.OPERADORRESTA,  yyline + 1, yycolumn + 1, yytext());
            }
          case 71: break;
          case 15: 
            { return new Symbol(sym.MAYORQUE,  yyline + 1, yycolumn + 1, yytext());
            }
          case 72: break;
          case 16: 
            { return new Symbol(sym.MENORQUE,  yyline + 1, yycolumn + 1, yytext());
            }
          case 73: break;
          case 17: 
            { return new Symbol(sym.COMA,  yyline + 1, yycolumn + 1, yytext());
            }
          case 74: break;
          case 18: 
            { return new Symbol(sym.CORCHETEIZQUIERDO,  yyline + 1, yycolumn + 1, yytext());
            }
          case 75: break;
          case 19: 
            { return new Symbol(sym.CORCHETEDERECHO,  yyline + 1, yycolumn + 1, yytext());
            }
          case 76: break;
          case 20: 
            { return new Symbol(sym.LLAVEIZQUIERDA,  yyline + 1, yycolumn + 1, yytext());
            }
          case 77: break;
          case 21: 
            { return new Symbol(sym.LLAVEDERECHA,  yyline + 1, yycolumn + 1, yytext());
            }
          case 78: break;
          case 22: 
            { return new Symbol(sym.AND,  yyline + 1, yycolumn + 1, yytext());
            }
          case 79: break;
          case 23: 
            { return new Symbol(sym.PUNTOYCOMA,  yyline + 1, yycolumn + 1, yytext());
            }
          case 80: break;
          case 24: 
            { return new Symbol(sym.PUNTO,  yyline + 1, yycolumn + 1, yytext());
            }
          case 81: break;
          case 25: 
            { return new Symbol(sym.DIVIGUAL,  yyline + 1, yycolumn + 1, yytext());
            }
          case 82: break;
          case 26: 
            { return new Symbol(sym.MULTIIGUAL,  yyline + 1, yycolumn + 1, yytext());
            }
          case 83: break;
          case 27: 
            { return new Symbol(sym.PERCENTAGE,  yyline + 1, yycolumn + 1, yytext());
            }
          case 84: break;
          case 28: 
            { return new Symbol(sym.PERCENTAGESTRING,  yyline + 1, yycolumn + 1, yytext());
            }
          case 85: break;
          case 29: 
            { return new Symbol(sym.PERCENTAGECHART,  yyline + 1, yycolumn + 1, yytext());
            }
          case 86: break;
          case 30: 
            { return new Symbol(sym.MODASIGNACION,  yyline + 1, yycolumn + 1, yytext());
            }
          case 87: break;
          case 31: 
            { return new Symbol(sym.CONSTSTR,  yyline + 1, yycolumn + 1, yytext());
            }
          case 88: break;
          case 32: 
            { return new Symbol(sym.OROR,  yyline + 1, yycolumn + 1, yytext());
            }
          case 89: break;
          case 33: 
            { return new Symbol(sym.IGUALQUE,  yyline + 1, yycolumn + 1, yytext());
            }
          case 90: break;
          case 34: 
            { return new Symbol(sym.NOTIGUAL,  yyline + 1, yycolumn + 1, yytext());
            }
          case 91: break;
          case 35: 
            { return new Symbol(sym.IF, yyline + 1, yycolumn + 1, yytext());
            }
          case 92: break;
          case 36: 
            { return new Symbol(sym.MASIGUAL,  yyline + 1, yycolumn + 1, yytext());
            }
          case 93: break;
          case 37: 
            { return new Symbol(sym.MASMAS,  yyline + 1, yycolumn + 1, yytext());
            }
          case 94: break;
          case 38: 
            { return new Symbol(sym.MENOSIGUAL,  yyline + 1, yycolumn + 1, yytext());
            }
          case 95: break;
          case 39: 
            { return new Symbol(sym.MENOSMENOS,  yyline + 1, yycolumn + 1, yytext());
            }
          case 96: break;
          case 40: 
            { return new Symbol(sym.MAYORIGUAL,  yyline + 1, yycolumn + 1, yytext());
            }
          case 97: break;
          case 41: 
            { return new Symbol(sym.MENORIGUAL,  yyline + 1, yycolumn + 1, yytext());
            }
          case 98: break;
          case 42: 
            { return new Symbol(sym.ANDAND,  yyline + 1, yycolumn + 1, yytext());
            }
          case 99: break;
          case 43: 
            { return new Symbol(sym.CONSTCHAR,  yyline + 1, yycolumn + 1, yytext());
            }
          case 100: break;
          case 44: 
            { return new Symbol(sym.INT,  yyline + 1, yycolumn + 1, yytext());
            }
          case 101: break;
          case 45: 
            { return new Symbol(sym.FOR,yyline + 1,yycolumn + 1, yytext());
            }
          case 102: break;
          case 46: 
            { return new Symbol(sym.CHAR,  yyline + 1, yycolumn + 1, yytext());
            }
          case 103: break;
          case 47: 
            { return new Symbol(sym.INTPUNT,  yyline + 1, yycolumn + 1, yytext());
            }
          case 104: break;
          case 48: 
            { return new Symbol(sym.MAIN,  yyline + 1, yycolumn + 1, yytext());
            }
          case 105: break;
          case 49: 
            { return new Symbol(sym.ELSE,yyline + 1, yycolumn + 1, yytext());
            }
          case 106: break;
          case 50: 
            { return new Symbol(sym.VOID,  yyline + 1, yycolumn + 1, yytext());
            }
          case 107: break;
          case 51: 
            { return new Symbol(sym.SCANF,  yyline + 1, yycolumn + 1, yytext());
            }
          case 108: break;
          case 52: 
            { return new Symbol(sym.CHARPUNT,  yyline + 1, yycolumn + 1, yytext());
            }
          case 109: break;
          case 53: 
            { return new Symbol(sym.WHILE, yyline + 1, yycolumn + 1, yytext());
            }
          case 110: break;
          case 54: 
            { return new Symbol(sym.BREAK,  yyline + 1, yycolumn + 1, yytext());
            }
          case 111: break;
          case 55: 
            { return new Symbol(sym.RETURN,  yyline + 1, yycolumn + 1, yytext());
            }
          case 112: break;
          case 56: 
            { return new Symbol(sym.IMPORT,  yyline + 1, yycolumn + 1, yytext());
            }
          case 113: break;
          case 57: 
            { return new Symbol(sym.PRINTF,  yyline + 1, yycolumn + 1, yytext());
            }
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
