
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 20 19:43:29 CST 2017
//----------------------------------------------------

package proyecto_compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 43;
  public static final int INTERROGACION = 39;
  public static final int SCANF = 28;
  public static final int OPERADORRELACIONAL = 37;
  public static final int CHAR = 3;
  public static final int PUNTOYCOMA = 41;
  public static final int INTPUNT = 4;
  public static final int OPERADORLOGICO = 40;
  public static final int CHARPUNT = 5;
  public static final int INT = 2;
  public static final int FOR = 10;
  public static final int PERCENTAGEDIGIT = 30;
  public static final int AND = 45;
  public static final int NOT = 26;
  public static final int IGUAL = 24;
  public static final int LLAVEDERECHA = 19;
  public static final int NUM = 32;
  public static final int MAIN = 13;
  public static final int IF = 7;
  public static final int CORCHETEIZQUIERDO = 16;
  public static final int ID = 6;
  public static final int PARAMETROSCANF = 44;
  public static final int PARENTESISDERECHO = 23;
  public static final int EOF = 0;
  public static final int OperARITMETICOIGUAL = 33;
  public static final int RETURN = 14;
  public static final int TRUE = 11;
  public static final int error = 1;
  public static final int COMA = 42;
  public static final int CONSTSTR = 21;
  public static final int VOID = 15;
  public static final int PRINTF = 27;
  public static final int IMPORT = 46;
  public static final int ELSE = 8;
  public static final int CORCHETEDERECHO = 17;
  public static final int PUNTO = 25;
  public static final int OPERADORSUMA = 34;
  public static final int WHILE = 9;
  public static final int MODARITMETICO = 38;
  public static final int PARENTESISIZQUIERDO = 22;
  public static final int PERCENTAGESTRING = 31;
  public static final int LLAVEIZQUIERDA = 18;
  public static final int CONSTCHAR = 20;
  public static final int MODASIGNACION = 36;
  public static final int PERCENTAGE = 29;
  public static final int FALSE = 12;
  public static final int OPERADORMULTIPLICACION = 35;
}

