
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 21 10:24:34 CST 2017
//----------------------------------------------------

package proyecto_compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 30;
  public static final int MENOSMENOS = 35;
  public static final int SCANF = 24;
  public static final int CHAR = 3;
  public static final int PUNTOYCOMA = 48;
  public static final int INTPUNT = 4;
  public static final int DIVIGUAL = 39;
  public static final int CHARPUNT = 5;
  public static final int INT = 2;
  public static final int FOR = 10;
  public static final int PERCENTAGEDIGIT = 25;
  public static final int OROR = 47;
  public static final int MENORIGUAL = 43;
  public static final int IGUALQUE = 45;
  public static final int MAYORQUE = 41;
  public static final int IGUAL = 22;
  public static final int MULTIIGUAL = 38;
  public static final int MASIGUAL = 36;
  public static final int OPERADORRESTA = 32;
  public static final int LLAVEDERECHA = 17;
  public static final int ANDAND = 46;
  public static final int NUM = 28;
  public static final int MAIN = 11;
  public static final int IF = 7;
  public static final int CORCHETEIZQUIERDO = 14;
  public static final int ID = 6;
  public static final int MAYORIGUAL = 42;
  public static final int PARENTESISDERECHO = 21;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int error = 1;
  public static final int COMA = 49;
  public static final int CONSTSTR = 19;
  public static final int BREAK = 29;
  public static final int OPERADORDIV = 34;
  public static final int VOID = 13;
  public static final int PRINTF = 23;
  public static final int MENORQUE = 40;
  public static final int ELSE = 8;
  public static final int CORCHETEDERECHO = 15;
  public static final int OPERADORSUMA = 31;
  public static final int WHILE = 9;
  public static final int PARENTESISIZQUIERDO = 20;
  public static final int PERCENTAGESTRING = 26;
  public static final int LLAVEIZQUIERDA = 16;
  public static final int MENOSIGUAL = 37;
  public static final int CONSTCHAR = 18;
  public static final int PERCENTAGECHART = 27;
  public static final int OPERADORMULTIPLICACION = 33;
  public static final int NOTIGUAL = 44;
}

