
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 14 15:49:56 CST 2017
//----------------------------------------------------

package proyecto_compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 8;
  public static final int MENOS = 3;
  public static final int POR = 4;
  public static final int ENTRE = 5;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int PARIZQ = 6;
  public static final int error = 1;
  public static final int PARDER = 7;
}

